name: Build Whisper.cpp for CoreELEC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Download Whisper.cpp Source
        run: |
          wget https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.5.1.tar.gz
          tar -xvf v1.5.1.tar.gz

      - name: Build Whisper.cpp
        run: |
          cd whisper.cpp-1.5.1
          # --- ГЛАВНОЕ ИСПРАВЛЕНИЕ ЗДЕСЬ ---
          # Мы "вырезаем" все флаги оптимизации x86 из Makefile
          sed -i 's/-mavx -mavx2 -mfma -mf16c -msse3 -mssse3/-DGGML_ARM_NO_FP16/g' Makefile
          # Теперь запускаем сборку с указанием нашего кросс-компилятора и флагом -static
          make main CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ LDFLAGS="-static"

      - name: Prepare Artifact
        run: |
          mkdir artifact
          cp whisper.cpp-1.5.1/main ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper-main-binary
          path: artifact
