name: Build Whisper.cpp for CoreELEC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Download Whisper.cpp Source
        run: |
          wget https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.4.0.tar.gz
          tar -xvf v1.4.0.tar.gz

      - name: Build Whisper.cpp
        run: |
          cd whisper.cpp-1.4.0
          # --- ФИНАЛЬНЫЙ ШАГ: ПРАВИЛЬНЫЙ ПРОЦЕСС СБОРКИ ---
          
          # 1. Компилируем все .c и .cpp файлы в объектные файлы .o
          aarch64-linux-gnu-gcc -I. -O3 -DNDEBUG -std=gnu11 -fPIC -pthread -D_GNU_SOURCE -c ggml.c -o ggml.o
          aarch64-linux-gnu-g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread -c whisper.cpp -o whisper.o
          aarch64-linux-gnu-g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread -c examples/common.cpp -o common.o
          aarch64-linux-gnu-g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread -c examples/common-ggml.cpp -o common-ggml.o
          aarch64-linux-gnu-g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread -c examples/main/main.cpp -o main.o
          
          # 2. "Склеиваем" все .o файлы вместе, чтобы создать исполняемый файл main
          aarch64-linux-gnu-g++ \
            -march=armv8-a \
            -o main \
            main.o \
            common.o \
            common-ggml.o \
            whisper.o \
            ggml.o \
            -static -pthread

      - name: Prepare Artifact
        run: |
          mkdir artifact
          cp whisper.cpp-1.4.0/main ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper-main-binary-final-v3
          path: artifact
