name: Build Whisper.cpp for CoreELEC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Download Whisper.cpp Source
        run: |
          wget https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.5.1.tar.gz
          tar -xvf v1.5.1.tar.gz

      - name: Build Whisper.cpp
        run: |
          cd whisper.cpp-1.5.1
          # --- ФИНАЛЬНЫЙ ШАГ: ПРАВИЛЬНЫЙ КОМПИЛЯТОР ДЛЯ КАЖДОГО ТИПА ФАЙЛОВ ---
          
          # 1. Компилируем все .c файлы в .o с помощью gcc (компилятор C)
          aarch64-linux-gnu-gcc -I. -O3 -DNDEBUG -std=c11 -fPIC -pthread -c ggml.c -o ggml.o
          aarch64-linux-gnu-gcc -I. -O3 -DNDEBUG -std=c11 -fPIC -pthread -c ggml-alloc.c -o ggml-alloc.o
          aarch64-linux-gnu-gcc -I. -O3 -DNDEBUG -std=c11 -fPIC -pthread -c ggml-backend.c -o ggml-backend.o
          aarch64-linux-gnu-gcc -I. -O3 -DNDEBUG -std=c11 -fPIC -pthread -c ggml-quants.c -o ggml-quants.o

          # 2. Компилируем .cpp файлы и "склеиваем" все вместе с помощью g++ (компилятор C++)
          aarch64-linux-gnu-g++ \
            -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread \
            -march=armv8-a \
            -o main \
            whisper.cpp \
            examples/common.cpp \
            examples/main/main.cpp \
            ggml.o ggml-alloc.o ggml-backend.o ggml-quants.o \
            -static

      - name: Prepare Artifact
        run: |
          mkdir artifact
          cp whisper.cpp-1.5.1/main ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper-main-binary-final
          path: artifact
