name: Build Whisper.cpp for CoreELEC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Download Whisper.cpp Source
        run: |
          wget https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.5.1.tar.gz
          tar -xvf v1.5.1.tar.gz

      - name: Build Whisper.cpp
        run: |
          cd whisper.cpp-1.5.1
          # --- ФИНАЛЬНОЕ ИСПРАВЛЕНИЕ: МЫ ИСКЛЮЧАЕМ ПРОБЛЕМНЫЙ ФАЙЛ ИЗ СБОРКИ ---
          aarch64-linux-gnu-g++ \
            -I. -I./examples \
            -O3 -DNDEBUG -std=c++11 -fPIC -pthread -D_GNU_SOURCE \
            -march=armv8-a \
            -o main \
            whisper.cpp \
            ggml.c \
            ggml-alloc.c \
            ggml-backend.c \
            examples/common.cpp \
            examples/main/main.cpp \
            -static

      - name: Prepare Artifact
        run: |
          mkdir artifact
          cp whisper.cpp-1.5.1/main ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper-main-binary-final
          path: artifact
